<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DEMON-PC" failures="2" tests="6" name="Test" time="67.879" errors="0" timestamp="2024-08-29T19:00:13 IST">
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="3.883"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="13.532"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="13.827"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="13.206"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="1.269">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="12.338">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
